name = "spooky-season-discord-add"
main = "functions/worker.mjs"
compatibility_date = "2025-11-01"

[vars]
ALLOWED_CHANNEL_ID = "1555415488983732255"
GITHUB_REPOSITORY_OWNER = "sage-afk"
GITHUB_REPOSITORY_NAME = "spooky-season"
GITHUB_BRANCH = "main"
DISCORD_APPLICATION_ID = "1555768866276118578"
DISCORD_TEST_GUILD_ID = "984255572394274888"
DISCORD_PUBLIC_KEY = "3a54076f6b9f22d63f0137f130cbf6389a4872fa5c1d81f2ee7805865db621da"